### ISSUE TITLE
Blank form fields not updating the model

### ISSUE THREAD

**Issue by grilix** [datapimp/luca#16]
When a model fails to save because of errors, and some field in the form is blanked after submit, the change is not applied to model attribute.
Consider a model Person with a name and last name, that requires a name length of five characters, then a form to save that model.
1. The user enters: name= "John", last_name="Doe", and submits the form.
2. The form fails.
3. The user changes the form to: name= "Albert", last_name= "", and submits the form.

Expected:
The saved model is {name="Albert", last_name=""}

Got:
The saved model is {name="Albert", last_name="Doe"}

**Comment by grilix** [comment]
@datapimp The option send_blanks is causing this. Do we really need this option? Don't we want blank fields to be always sent?
We can fix the issue by removing this option, what do you think?

**Comment by grilix** [comment]
@datapimp Can you take a look at grilix/luca@9cc0983b94db0e6c896f816d684ec5bff79757ab?

**Comment by datapimp** [comment]
this would break some production apps unfortunately.

i would have to go through and look but there are cases where it would have undesired effects ( checkboxes and a few other places come to mind )

i made it configurable -- the configuration api could definitely be cleaned up and more easily readable.  but you should be able to specify on your formView which behavior your want by default.
